name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint bandit unittest2

    - name: Static Analysis (flake8)
      run: |
        flake8 shopping_cart.py

    - name: Static Analysis (pylint)
      run: |
        pylint shopping_cart.py || true

    - name: Security Check (bandit)
      run: |
        bandit -r shopping_cart.py

    - name: Run Tests
      run: |
        python -m unittest discover
